################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: true

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    swarmMode: true

  file:
    filename: /etc/traefik/traefik_dynamic.yml

################################################################
# Traefik Logging
################################################################
# log:
#   level: INFO

################################################################
# Enable Healthcheck
################################################################
ping: {}


